package com.outis.realstate.ai.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ChatInteractionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatInteractionAllPropertiesEquals(ChatInteraction expected, ChatInteraction actual) {
        assertChatInteractionAutoGeneratedPropertiesEquals(expected, actual);
        assertChatInteractionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatInteractionAllUpdatablePropertiesEquals(ChatInteraction expected, ChatInteraction actual) {
        assertChatInteractionUpdatableFieldsEquals(expected, actual);
        assertChatInteractionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatInteractionAutoGeneratedPropertiesEquals(ChatInteraction expected, ChatInteraction actual) {
        assertThat(actual)
            .as("Verify ChatInteraction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatInteractionUpdatableFieldsEquals(ChatInteraction expected, ChatInteraction actual) {
        assertThat(actual)
            .as("Verify ChatInteraction relevant properties")
            .satisfies(a -> assertThat(a.getEntityId()).as("check entityId").isEqualTo(expected.getEntityId()))
            .satisfies(a -> assertThat(a.getEntityName()).as("check entityName").isEqualTo(expected.getEntityName()))
            .satisfies(a -> assertThat(a.getCustomerQuestion()).as("check customerQuestion").isEqualTo(expected.getCustomerQuestion()))
            .satisfies(a -> assertThat(a.getChatbotAnswer()).as("check chatbotAnswer").isEqualTo(expected.getChatbotAnswer()))
            .satisfies(a -> assertThat(a.getTimestamp()).as("check timestamp").isEqualTo(expected.getTimestamp()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatInteractionUpdatableRelationshipsEquals(ChatInteraction expected, ChatInteraction actual) {
        // empty method
    }
}
