package com.outis.realstate.ai.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RAGContextAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRAGContextAllPropertiesEquals(RAGContext expected, RAGContext actual) {
        assertRAGContextAutoGeneratedPropertiesEquals(expected, actual);
        assertRAGContextAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRAGContextAllUpdatablePropertiesEquals(RAGContext expected, RAGContext actual) {
        assertRAGContextUpdatableFieldsEquals(expected, actual);
        assertRAGContextUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRAGContextAutoGeneratedPropertiesEquals(RAGContext expected, RAGContext actual) {
        assertThat(actual)
            .as("Verify RAGContext auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRAGContextUpdatableFieldsEquals(RAGContext expected, RAGContext actual) {
        assertThat(actual)
            .as("Verify RAGContext relevant properties")
            .satisfies(a -> assertThat(a.getEntityId()).as("check entityId").isEqualTo(expected.getEntityId()))
            .satisfies(a -> assertThat(a.getEntityName()).as("check entityName").isEqualTo(expected.getEntityName()))
            .satisfies(a -> assertThat(a.getContextText()).as("check contextText").isEqualTo(expected.getContextText()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRAGContextUpdatableRelationshipsEquals(RAGContext expected, RAGContext actual) {
        // empty method
    }
}
