package com.outis.realstate.properties.domain;

import static com.outis.realstate.properties.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SaleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaleAllPropertiesEquals(Sale expected, Sale actual) {
        assertSaleAutoGeneratedPropertiesEquals(expected, actual);
        assertSaleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaleAllUpdatablePropertiesEquals(Sale expected, Sale actual) {
        assertSaleUpdatableFieldsEquals(expected, actual);
        assertSaleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaleAutoGeneratedPropertiesEquals(Sale expected, Sale actual) {
        assertThat(actual)
            .as("Verify Sale auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaleUpdatableFieldsEquals(Sale expected, Sale actual) {
        assertThat(actual)
            .as("Verify Sale relevant properties")
            .satisfies(a -> assertThat(a.getPropertyId()).as("check propertyId").isEqualTo(expected.getPropertyId()))
            .satisfies(a -> assertThat(a.getCustomerId()).as("check customerId").isEqualTo(expected.getCustomerId()))
            .satisfies(a -> assertThat(a.getOportunityId()).as("check oportunityId").isEqualTo(expected.getOportunityId()))
            .satisfies(a -> assertThat(a.getSaleDate()).as("check saleDate").isEqualTo(expected.getSaleDate()))
            .satisfies(a ->
                assertThat(a.getTotalAmount())
                    .as("check totalAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalAmount())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaleUpdatableRelationshipsEquals(Sale expected, Sale actual) {
        // empty method
    }
}
