configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: N2ExYTRiYjU1ZmJmYTFmN2MzZWU3OWZjNTg5OGUyNGJmOWE1NzE3YTg0YzQ4NGMzNWU4ZTU4OTc1YzQzOWVhNzc3NWQyYTBjZTZhZDZmODgyMTA3MDk0NzZmMTMzNjA5YjUzNDRkY2ZjY2Y5NzQ5NDAxYzY1OThlYTBmNWZmNzk=
