# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: crmrealstate
services:
  postgresql:
    image: postgres:17.2
    env_file:
      - .env

    volumes:
      - ${POSTGRES_DATA_DIR:-$HOME/volumes/jhipster/crmRealState/postgresql}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=crmRealState
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=md5
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $$POSTGRES_DB']
      interval: 5s
      timeout: 5s
      retries: 10
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
