configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NWFhNzgxN2Q5Nzg5NDhhZGFjNzE1NDk3YTBlMjU3YTYyNjU4NjExNzA5MDE4OTg4MDNlM2U4MjNlY2FiM2I5Yjk5ZTcwODdlNTNkNWU2ZTVkN2VmMGNlZGMyNjJjMTM4MTIzYmI5MTdjYWYzYzQxODUwOTQ1YzNkZDQxMWMzNjE=
