package com.outis.crm.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ChatInteractionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatInteractionAllPropertiesEquals(ChatInteraction expected, ChatInteraction actual) {
        assertChatInteractionAutoGeneratedPropertiesEquals(expected, actual);
        assertChatInteractionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatInteractionAllUpdatablePropertiesEquals(ChatInteraction expected, ChatInteraction actual) {
        assertChatInteractionUpdatableFieldsEquals(expected, actual);
        assertChatInteractionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatInteractionAutoGeneratedPropertiesEquals(ChatInteraction expected, ChatInteraction actual) {
        assertThat(actual)
            .as("Verify ChatInteraction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatInteractionUpdatableFieldsEquals(ChatInteraction expected, ChatInteraction actual) {
        assertThat(actual)
            .as("Verify ChatInteraction relevant properties")
            .satisfies(a -> assertThat(a.getCustomerMessage()).as("check customerMessage").isEqualTo(expected.getCustomerMessage()))
            .satisfies(a -> assertThat(a.getChatbotResponse()).as("check chatbotResponse").isEqualTo(expected.getChatbotResponse()))
            .satisfies(a -> assertThat(a.getTimestamp()).as("check timestamp").isEqualTo(expected.getTimestamp()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatInteractionUpdatableRelationshipsEquals(ChatInteraction expected, ChatInteraction actual) {
        assertThat(actual)
            .as("Verify ChatInteraction relationships")
            .satisfies(a -> assertThat(a.getCustomer()).as("check customer").isEqualTo(expected.getCustomer()));
    }
}
