package com.outis.crm.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ChatInteractionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatInteractionAllPropertiesEquals(ChatInteraction expected, ChatInteraction actual) {
        assertChatInteractionAutoGeneratedPropertiesEquals(expected, actual);
        assertChatInteractionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatInteractionAllUpdatablePropertiesEquals(ChatInteraction expected, ChatInteraction actual) {
        assertChatInteractionUpdatableFieldsEquals(expected, actual);
        assertChatInteractionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatInteractionAutoGeneratedPropertiesEquals(ChatInteraction expected, ChatInteraction actual) {
        assertThat(expected)
            .as("Verify ChatInteraction auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatInteractionUpdatableFieldsEquals(ChatInteraction expected, ChatInteraction actual) {
        assertThat(expected)
            .as("Verify ChatInteraction relevant properties")
            .satisfies(e -> assertThat(e.getCustomerMessage()).as("check customerMessage").isEqualTo(actual.getCustomerMessage()))
            .satisfies(e -> assertThat(e.getChatbotResponse()).as("check chatbotResponse").isEqualTo(actual.getChatbotResponse()))
            .satisfies(e -> assertThat(e.getTimestamp()).as("check timestamp").isEqualTo(actual.getTimestamp()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatInteractionUpdatableRelationshipsEquals(ChatInteraction expected, ChatInteraction actual) {
        assertThat(expected)
            .as("Verify ChatInteraction relationships")
            .satisfies(e -> assertThat(e.getCustomer()).as("check customer").isEqualTo(actual.getCustomer()));
    }
}
