package com.outis.crm.domain;

import static com.outis.crm.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class OpportunityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpportunityAllPropertiesEquals(Opportunity expected, Opportunity actual) {
        assertOpportunityAutoGeneratedPropertiesEquals(expected, actual);
        assertOpportunityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpportunityAllUpdatablePropertiesEquals(Opportunity expected, Opportunity actual) {
        assertOpportunityUpdatableFieldsEquals(expected, actual);
        assertOpportunityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpportunityAutoGeneratedPropertiesEquals(Opportunity expected, Opportunity actual) {
        assertThat(expected)
            .as("Verify Opportunity auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpportunityUpdatableFieldsEquals(Opportunity expected, Opportunity actual) {
        assertThat(expected)
            .as("Verify Opportunity relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getBudget()).as("check budget").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getBudget()))
            .satisfies(e -> assertThat(e.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getAmount()))
            .satisfies(e -> assertThat(e.getProbability()).as("check probability").isEqualTo(actual.getProbability()))
            .satisfies(e -> assertThat(e.getExpectedCloseDate()).as("check expectedCloseDate").isEqualTo(actual.getExpectedCloseDate()))
            .satisfies(e -> assertThat(e.getStage()).as("check stage").isEqualTo(actual.getStage()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getCreatedAt()).as("check createdAt").isEqualTo(actual.getCreatedAt()))
            .satisfies(e -> assertThat(e.getModifiedAt()).as("check modifiedAt").isEqualTo(actual.getModifiedAt()))
            .satisfies(e -> assertThat(e.getClosedAt()).as("check closedAt").isEqualTo(actual.getClosedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpportunityUpdatableRelationshipsEquals(Opportunity expected, Opportunity actual) {
        assertThat(expected)
            .as("Verify Opportunity relationships")
            .satisfies(e -> assertThat(e.getCustomer()).as("check customer").isEqualTo(actual.getCustomer()))
            .satisfies(e -> assertThat(e.getProperty()).as("check property").isEqualTo(actual.getProperty()));
    }
}
