package com.outis.crm.domain;

import static com.outis.crm.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class QuotationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotationAllPropertiesEquals(Quotation expected, Quotation actual) {
        assertQuotationAutoGeneratedPropertiesEquals(expected, actual);
        assertQuotationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotationAllUpdatablePropertiesEquals(Quotation expected, Quotation actual) {
        assertQuotationUpdatableFieldsEquals(expected, actual);
        assertQuotationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotationAutoGeneratedPropertiesEquals(Quotation expected, Quotation actual) {
        assertThat(expected)
            .as("Verify Quotation auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotationUpdatableFieldsEquals(Quotation expected, Quotation actual) {
        assertThat(expected)
            .as("Verify Quotation relevant properties")
            .satisfies(e ->
                assertThat(e.getFinalPrice()).as("check finalPrice").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getFinalPrice())
            )
            .satisfies(e -> assertThat(e.getValidityDate()).as("check validityDate").isEqualTo(actual.getValidityDate()))
            .satisfies(e -> assertThat(e.getComments()).as("check comments").isEqualTo(actual.getComments()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotationUpdatableRelationshipsEquals(Quotation expected, Quotation actual) {
        assertThat(expected)
            .as("Verify Quotation relationships")
            .satisfies(e -> assertThat(e.getCustomer()).as("check customer").isEqualTo(actual.getCustomer()))
            .satisfies(e -> assertThat(e.getProperty()).as("check property").isEqualTo(actual.getProperty()));
    }
}
